name: PAX East 2016
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24154
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#410f12'
    - '#fe819f'
    - '#999eb2'
    - '#8c5d49'
    - '#fffdf7'
  brandStrength: 0.08827204164117575
  lightness: 0.28030123724602163
  saturation: 0.6294829936232418
  rhythmicContrast: 0.4360829999204725
purpose: []
